services:
  crossdev:
    container_name: "${COMPOSE_PROJECT_NAME:?err}"
    hostname: "${COMPOSE_PROJECT_NAME:?err}"
    image: ${CROSSDEV_IMAGE:-luoyuhao0x58/crossdev:latest}
    build:
      context: ./src/crossdev
      dockerfile: Dockerfile
      args:
        CROSSDEV_USER_ID: "${CROSSDEV_USER_ID:?err}"
        CROSSDEV_USER_NAME: "${CROSSDEV_USER_NAME:?err}"
        CROSSDEV_USER_HOME: "${CROSSDEV_USER_HOME:?err}"
        CROSSDEV_BUILD_CONFIGS: ${CROSSDEV_BUILD_CONFIGS:?err}
    environment:
      CROSSDEV_GIT_AUTHOR_NAME: "${CROSSDEV_GIT_AUTHOR_NAME:-}"
      CROSSDEV_GIT_AUTHOR_EMAIL: "${CROSSDEV_GIT_AUTHOR_EMAIL:-}"
      CROSSDEV_GIT_SIGNINGKEY: "${CROSSDEV_GIT_SIGNINGKEY:-}"
    volumes:
      - type: volume
        source: data_hostkey
        target: /etc/ssh/hostkey
      - type: volume
        source: data_vscode
        target: "${CROSSDEV_USER_HOME:?err}/.vscode-server"

volumes:
  data_hostkey:
  data_vscode:
