x-v-user-name: &v-user-name ${BUILDER:-crossdev}
x-v-user-home: &v-user-home ${BUILDER_HOME:-/.crossdev}
x-v-vscode-path: &v-vscode-path ${BUILDER_HOME:-/.crossdev}/.vscode-server


services:
  crossdev:
    container_name: "${COMPOSE_PROJECT_NAME:?err}"
    hostname: "${COMPOSE_PROJECT_NAME:?err}"
    image: ${IMAGE:-luoyuhao0x58/crossdev:latest}
    build:
      context: ./crossdev
      dockerfile: Dockerfile
      # platforms:
      #   - "linux/amd64"
      #   - "linux/arm64"
      args:
        BUILDER: *v-user-name
        BUILDER_HOME: *v-user-home
        CONFIGS: ${CONFIGS:?err}
    environment:
      GIT_AUTHOR_NAME: "${GIT_AUTHOR_NAME:-}"
      GIT_AUTHOR_EMAIL: "${GIT_AUTHOR_EMAIL:-}"
      GIT_SIGNINGKEY: "${GIT_SIGNINGKEY:-}"
      USER_NAME: "${USER_NAME:-}"
      USER_HOME: "${USER_HOME:-}"
    volumes:
      - type: volume
        source: data_hostkey
        target: /etc/ssh/hostkey
      - type: volume
        source: data_vscode
        target: *v-vscode-path


volumes:
  data_hostkey:
  data_vscode:
