name: Docker Image CI

on:
  workflow_dispatch:
  # push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Free Disk Space Before Build
        run: |
          echo "Disk space before cleanup:"
          df -h
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android/sdk/ndk
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo apt-get clean
          echo "Disk space after cleanup:"
          df -h
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src/crossdev
          pull: true
          push: true
          no-cache: true
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            STABLE_NETWORK=1
            CROSSDEV_BUILD_CONFIGS=${{ vars.CROSSDEV_BUILD_CONFIGS }}
            CROSSDEV_USER_HOME=${{ vars.CROSSDEV_USER_HOME }}
            CROSSDEV_USER_NAME=${{ vars.CROSSDEV_USER_NAME }}
            CROSSDEV_USER_ID=${{ vars.CROSSDEV_USER_ID }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest
